### ISSUE TITLE
App crashes after _purchaser.InitializePurchasing();

### ISSUE THREAD

**Issue by nenovmy** [Aptoide/bds-unity-plugin#5]
After I tried to buy an IAP item the transaction took forever. The next time I started the app it crashed right away (after _purchaser.InitializePurchasing(); is called) with this error:

`10-23 13:29:49.362: E/ActivityThread(7895): Activity com.unity3d.player.UnityPlayerActivity has leaked ServiceConnection null that was originally bound here
10-23 13:29:49.362: E/ActivityThread(7895): android.app.ServiceConnectionLeaked: Activity com.unity3d.player.UnityPlayerActivity has leaked ServiceConnection null that was originally bound here
10-23 13:29:49.362: E/ActivityThread(7895): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1538)
10-23 13:29:49.362: E/ActivityThread(7895): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1430)
10-23 13:29:49.362: E/ActivityThread(7895): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1622)
10-23 13:29:49.362: E/ActivityThread(7895): 	at android.app.ContextImpl.bindService(ContextImpl.java:1574)
10-23 13:29:49.362: E/ActivityThread(7895): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:697)
10-23 13:29:49.362: E/ActivityThread(7895): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
10-23 13:29:49.362: E/ActivityThread(7895): 	at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
10-23 13:29:49.362: E/ActivityThread(7895): 	at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
10-23 13:29:49.362: E/ActivityThread(7895): 	at android.os.MessageQueue.next(MessageQueue.java:394)
10-23 13:29:49.362: E/ActivityThread(7895): 	at android.os.Looper.loop(Looper.java:142)
10-23 13:29:49.362: E/ActivityThread(7895): 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
`

**Comment by nenovmy** [comment]
Setup:

Unity version: 2018.2.13f1
BDS unity plugin: 1.0.1
Wallet version: 1.1.1.4

Testing on Samsung galaxy s7 edge with Android 8.0.0

**Comment by nenovmy** [comment]
[Color Spint Appcoins Test.zip](https://github.com/Aptoide/bds-unity-plugin/files/2507495/Color.Spint.Appcoins.Test.zip)
This is a minimal project that reproduces the issue. It has only one script that just enables a button when the purchasing is initialised. The first time purchasing remove ads works and then crashes. When started again it crashes right away...

**Comment by nenovmy** [comment]
One more exception I saw in LogCat:

10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): Exception found
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String cm.aptoide.pt.database.realm.Update.getPackageName()' on a null object reference
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at cm.aptoide.pt.updates.UpdateRepository.lambda$remove$15(UpdateRepository.java:203)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at cm.aptoide.pt.updates.UpdateRepository$$Lambda$14.call(Unknown Source:4)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.a$21.a(Completable.java:469)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.a$21.call(Completable.java:463)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.a.a(Completable.java:2037)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.CompletableOnSubscribeConcatArray$ConcatInnerSubscriber.b(CompletableOnSubscribeConcatArray.java:92)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.CompletableOnSubscribeConcatArray$ConcatInnerSubscriber.a(CompletableOnSubscribeConcatArray.java:68)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.a$2$1.onCompleted(Completable.java:577)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.OnSubscribeFlatMapCompletable$FlatMapCompletableSubscriber.a(OnSubscribeFlatMapCompletable.java:142)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.OnSubscribeFlatMapCompletable$FlatMapCompletableSubscriber.onCompleted(OnSubscribeFlatMapCompletable.java:133)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.i$a.a(OnSubscribeFlattenIterable.java:305)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.i$a.a(OnSubscribeFlattenIterable.java:177)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.i$a.onCompleted(OnSubscribeFlattenIterable.java:144)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.producers.SingleProducer.request(SingleProducer.java:75)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.i.setProducer(Subscriber.java:211)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.af$b.onCompleted(OperatorSingle.java:110)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.ak$1.onNext(OperatorTake.java:80)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.ai$a.onNext(OperatorSubscribeOn.java:74)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.OperatorMerge$d.a(OperatorMerge.java:395)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.OperatorMerge$d.a(OperatorMerge.java:355)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.OperatorMerge$c.onNext(OperatorMerge.java:846)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.operators.ac$a.call(OperatorObserveOn.java:224)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.schedulers.a$b$1.call(CachedThreadScheduler.java:230)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-23 20:23:33.245: E/cm.aptoide.pt.crashreports.ConsoleLogger(28682): 	at java.lang.Thread.run(Thread.java:764)

**Comment by nenovmy** [comment]
I also noticed this exception:

10-24 11:47:12.811 19756 19948 E IABUtil/Security: Invalid key specification.
10-24 11:47:12.812 19756 19948 E AndroidRuntime: FATAL EXCEPTION: Thread-8
10-24 11:47:12.812 19756 19948 E AndroidRuntime: Process: com.nenoff.colorspin, PID: 19756
10-24 11:47:12.812 19756 19948 E AndroidRuntime: java.lang.IllegalArgumentException: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0c0000be:ASN.1 encoding routines:OPENSSL_internal:WRONG_TAG
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	at com.aptoide.appcoinsunity.util.Security.generatePublicKey(Security.java:67)
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	at com.aptoide.appcoinsunity.util.Security.verifyPurchase(Security.java:47)
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	at com.aptoide.appcoinsunity.util.IabHelper.queryPurchases(IabHelper.java:1031)
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	at com.aptoide.appcoinsunity.util.IabHelper.queryInventory(IabHelper.java:664)
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	at com.aptoide.appcoinsunity.util.IabHelper$2.run(IabHelper.java:739)
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
10-24 11:47:12.812 19756 19948 E AndroidRuntime: Caused by: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0c0000be:ASN.1 encoding routines:OPENSSL_internal:WRONG_TAG
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:290)
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic(OpenSSLRSAKeyFactory.java:54)
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	at java.security.KeyFactory.generatePublic(KeyFactory.java:357)
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	at com.aptoide.appcoinsunity.util.Security.generatePublicKey(Security.java:62)
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	... 5 more
10-24 11:47:12.812 19756 19948 E AndroidRuntime: Caused by: java.lang.RuntimeException: error:0c0000be:ASN.1 encoding routines:OPENSSL_internal:WRONG_TAG
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	at com.android.org.conscrypt.NativeCrypto.d2i_PUBKEY(Native Method)
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:288)
10-24 11:47:12.812 19756 19948 E AndroidRuntime: 	... 8 more

**Comment by nenovmy** [comment]
I tested on another device with empty wallet and there are no exceptions at all. The games starts and I can click on the buy button. The appcoins dialog is shown and I can click on buy now and see the CC form (as I could on my first device before I bought something).

**Comment by nenovmy** [comment]
Any news on this issue?

**Comment by nunomonteiro** [comment]
Developer had input the wrong public key and plugin wasn't dealing properly with the Security exception on the java side. This is fixed now. 
Inputing a key that does not have the proper format will raise an exception that is dealt with and a proper error is returned to the plugin instead of it failing silently.
