### ISSUE TITLE
In-App with credit not working

### ISSUE THREAD

**Issue by megasoft78** [Aptoide/bds-unity-plugin#7]
Hi,
I tried to do an in-app when I have some credit but not enough for the in-app.
The first time I get "On purchase failed called with product" and the second one it close the game.

I tried with old and new sdk and I'm getting the same behaviours.
AppCoins Wallet is the last one.

**Comment by nunomonteiro** [comment]
Hello,
Sorry for the late reply. After internal talks with the team, I figured this issue is related to the wallet and not the plugin by itself.
Could you please post it here: 
https://github.com/Aptoide/appcoins-wallet-android/issues/
Thanks!
